### ISSUE TITLE
Current ToDo list

### ISSUE THREAD

**Issue by RDAxRoadkill** [RDAxRoadkill/IVT2.2Indi#2]
## Setup Project ##
- [ ] Setup basic client structure
- [ ] Setup basic server structure
- [ ] Setup MongoDB database
- [ ] Create MongoDB connection
- [ ] Setup Neo4j database
- [ ] Create Neo4j connection
## Functionalities ##
- [ ] Create CRUD operations for all namespaces
- [ ] Create Register/Login operations
## UI ##
- [ ] Link NodeJS and Angular properly
- [ ] Create landing page
- [ ] Create data retrieval page
